from tkinter import *
window=Tk()
e1=Entry(window)
e1.grid(row=0,columnspan=4)
button1=Button(window,text='1',command=lambda:addnumber(1))
button1.grid(row=4,column=0)
button2=Button(window,text='2',command=lambda:addnumber(2))
button2.grid(row=4,column=1)
button3=Button(window,text='3',command=lambda:addnumber(3))
button3.grid(row=4,column=2)
button4=Button(window,text='4',command=lambda:addnumber(4))
button4.grid(row=3,column=0)
button5=Button(window,text='5',command=lambda:addnumber(5))
button5.grid(row=3,column=1)
button6=Button(window,text='6',command=lambda:addnumber(6))
button6.grid(row=3,column=2)
button7=Button(window,text='7',command=lambda:addnumber(7))
button7.grid(row=2,column=0)
button8=Button(window,text='8',command=lambda:addnumber(8))
button8.grid(row=2,column=1)
button9=Button(window,text='9',command=lambda:addnumber(9))
button9.grid(row=2,column=2)
button0=Button(window,text='0',command=lambda:addnumber(0))
button0.grid(row=5,column=1)
button_plus=Button(window,text='+',command=lambda:addoperator('+'))
button_minus=Button(window,text='-',command=lambda:addoperator('-'))
button_mul=Button(window,text='*',command=lambda:addoperator('*'))
button_divide=Button(window,text='/',command=lambda:addoperator('/'))
button_modulo=Button(window,text='%',command=lambda:addoperator('%'))
button_equal=Button(window,text='=',command=lambda:equals())
button_dot=Button(window,text='.',command=lambda:addoperator('.'))
button_ac=Button(window,text='AC',command=lambda:clear())
button_del=Button(window,text='DEL',command=lambda:delete())
button_plus.grid(row=4,column=3)
button_minus.grid(row=3,column=3)
button_mul.grid(row=2,column=3)
button_divide.grid(row=1,column=3)
button_modulo.grid(row=1,column=2)
button_equal.grid(row=5,column=2,columnspan=2)
button_dot.grid(row=5,column=0)
button_ac.grid(row=1,column=0)
button_del.grid(row=1,column=1)
def addnumber(n):
    e1.insert(len(e1.get()),n)
def addoperator(m):
    e1.insert(len(e1.get()),m)
def equals():
    c=e1.get()
    e1.delete(0,END)
    e1.insert(0,eval(c))
def clear():
    e1.delete(0,END)
def delete():
    e1.delete(len(e1.get())-1,END)
mainloop()